
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_client_id: ${{ secrets.APP_ID }}
          TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.TENANT }}
