name: Terraform Azure Setup

on:
  #push:
  #  branches: ["master"]
  #pull_request:
  #  branches: ["master"]
  workflow_dispatch:

jobs:
  setup_container:
    runs-on: ubuntu-latest
    name: Perform Terraform Cycle
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare container ready
        uses: ./
      - name: install conftest
        run: |
            wget https://github.com/open-policy-agent/conftest/releases/download/v0.23.0/conftest_0.23.0_Linux_x86_64.tar.gz
            tar xzf conftest_0.23.0_Linux_x86_64.tar.gz
            mkdir -p $HOME/.local/bin
            mv conftest $HOME/.local/bin
            echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Terraform Init, Plan and run conftest
        run: |
            terraform init
            terraform plan -out=tfplan
            terraform show -json ./tfplan > tfplan.json
            echo "::set-output name=mix-test::$(conftest test ./tfplan.json)"
        id: run_tests
        env:
          TF_VAR_client_id: ${{ secrets.APP_ID }}
          TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.TENANT }}
      - name: Store in log
        run: |
            pip install PyGithub
            python hi.py ${{join(steps.run_tests.outputs.mix-test, ' ')}}
            exit 1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_client_id: ${{ secrets.APP_ID }}
          TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.TENANT }}
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_client_id: ${{ secrets.APP_ID }}
          TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.TENANT }}
